### PR TITLE
Fix TS errors in profile page and add some types

### LINKED ISSUE #32: Fix general TS errors and unhandled null/edge cases on the profile page
image

We should handle such errors.

### PR DESCRIPTION
**Pull request by Dhaiwat10**
Closes #32 

- Added optional chaining wherever possible to avoid errors caused by null states.
- Added some type declarations in a new `types.ts` file.

### CODE REVIEW

File: packages/dapp/src/pages/profile/[id]/index.tsx [hunk 1]
```diff
@@ -118,44 +113,46 @@ const Home = () => {
...
-                      bgColor="purple.600"
-                      textAlign="center"
-                      size="lg"
-                      key={index}
-                      minWidth="fit-content"
-                    >
-                      {skill}
-                    </Tag>
-                  ))}
+                  {publicProfile?.skillTags.map(
```
Comment (damianmarti) [inline packages/dapp/src/pages/profile/[id]/index.tsx:143]: I think we should check for publicProfile?.skillTags too.

**Review by damianmarti — CHANGES_REQUESTED** [review]
Great improvements!! Just a minor comment.

File: packages/dapp/src/pages/profile/[id]/index.tsx (hunk 1 above)
Comment (Dhaiwat10) [reply packages/dapp/src/pages/profile/[id]/index.tsx:143]: > I think we should check for publicProfile?.skillTags too.

Can `skillTags` be `undefined`? If it's an empty array, map will account for it

Comment (damianmarti) [reply packages/dapp/src/pages/profile/[id]/index.tsx:143]: I got an error from one profile the other day because skillTags was null. We can add this check to avoid an error.

**Comment by Dhaiwat10** [comment]
Feel free to merge if everything looks good @damianmarti

**Review by damianmarti — APPROVED** [review]
Great! Thanks!
